# Allow the operator to manage resources in its own namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-metrics-exporter
  namespace: openshift-machine-api
subjects:
  - kind: ServiceAccount
    name: osd-metrics-exporter
    namespace: openshift-osd-metrics
roleRef:
  kind: Role
  name: osd-metrics-exporter
  apiGroup: rbac.authorization.k8s.io

