kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-metrics-exporter
subjects:
  - kind: ServiceAccount
    name: osd-metrics-exporter
    namespace: openshift-osd-metrics
roleRef:
  kind: ClusterRole
  name: osd-metrics-exporter
  apiGroup: rbac.authorization.k8s.io
